@startuml
left to right direction
skinparam packageStyle rectangle

actor "Psicólogo" as User
actor "Sistema de Notificação" as SMS << Service >>

rectangle "Sistema de Gestão Clínica" {
    usecase "Cadastrar Paciente" as UC1
    usecase "Manter Prontuário Eletrônico" as UC2
    usecase "Visualizar Histórico Terapêutico" as UC3
    usecase "Agendar Consulta" as UC4
}

User --> UC1
User --> UC2
User --> UC3
User --> UC4

UC4 ..> SMS : <<extend>>
@enduml